### ISSUE TITLE
Bounding box error

### ISSUE THREAD

**Issue by SnallQiu** [f3rm/f3rm#12]
Hi, i change the setting in  args.py to fix my workspace, but it seems error. And it has nothing to do with the dataset, since it makes error even in your dataset(scene_001).
My test setting is:
`
min_bounds: Tuple[float, float, float] = (-0.4 -0.4, 0.005)
`
`
max_bounds: Tuple[float, float, float] = (0.6, 0.8, 0.4)
`
> Traceback (most recent call last):
  File "/home/ustc/venv/f3rm/bin/f3rm-optimize", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/ustc/qiuqc/grasp/f3rm/f3rm_robot/optimize.py", line 417, in entrypoint
    results = language_pose_optimization(feature_field, clip_model, query, device)
  File "/home/ustc/qiuqc/grasp/f3rm/f3rm_robot/optimize.py", line 226, in language_pose_optimization
    voxel_grid, voxel_sims, metrics["num_voxels"] = get_initial_voxel_grid(feature_field, query, clip_model, device)
  File "/home/ustc/qiuqc/grasp/f3rm/f3rm_robot/optimize.py", line 112, in get_initial_voxel_grid
    voxel_grid = voxel_grid.reshape(-1, 3)
RuntimeError: shape '[-1, 3]' is invalid for input of size 22400

change another setting will cost:
> Traceback (most recent call last):
  File "/home/ustc/venv/f3rm/bin/f3rm-optimize", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/ustc/qiuqc/grasp/f3rm/f3rm_robot/optimize.py", line 417, in entrypoint
    results = language_pose_optimization(feature_field, clip_model, query, device)
  File "/home/ustc/qiuqc/grasp/f3rm/f3rm_robot/optimize.py", line 226, in language_pose_optimization
    voxel_grid, voxel_sims, metrics["num_voxels"] = get_initial_voxel_grid(feature_field, query, clip_model, device)
  File "/home/ustc/qiuqc/grasp/f3rm/f3rm_robot/optimize.py", line 120, in get_initial_voxel_grid
    alpha_vg = alpha.reshape(og_voxel_grid_shape[:-1])
RuntimeError: shape '[140, 90]' is invalid for input of size 8400

**Comment by williamshen-nz** [comment]
You forgot the comma between the -0.4, so the `min_bounds` tuple is actually `(-0.8, 0.005)` which is invalid.

```bash
>>> from typing import Tuple
>>> min_bounds: Tuple[float, float, float] = (-0.4 -0.4, 0.005)
>>> min_bounds
(-0.8, 0.005)
```

I have added extra validation checks which make sure the bounds are of length 3 and `min_bounds` are smaller than `max_bounds`,  so this issue is more easily surfaced: https://github.com/f3rm/f3rm/commit/24e2b100017d393359ebe4e25536cdb3eeef84de

**Comment by SnallQiu** [comment]
Thank you! It's my mistake.
